DROP TABLE [dbo].[uid1]
GO
DROP TABLE [dbo].[uid2]
GO
CREATE TABLE [dbo].[uid1](
	[id] [uniqueidentifier] NOT NULL,
	[v] varchar(255),
	[ts] [timestamp] NOT NULL,
 CONSTRAINT [PK_uid1] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[uid2](
	[id] [uniqueidentifier] NOT NULL,
	[v] varchar(255),
	[ts] [timestamp] NOT NULL,
 CONSTRAINT [PK_uid2] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
